name: 'Up-To-IPFS-Use-Crust'
description: 'Upload your site to crustwebsites.net/ gateway'
author: 'Eericxu'
branding:
  icon: 'upload'
  color: 'gray-dark'

inputs:
  path:
    description: 'Path to directory which should be sent to gateway'
    required: true
  crust-secret-key:
    description: 'Crustwebsites gateway secret key'
    required: true
  ipns-key:
    description: 'ipns-key is (ipfs key gen <ipns-key>)'
    default: ''
    required: false

outputs:
  hash:
    description: 'Uploaded IPFS cid(CIDv0) hash value'
  ipns:
    description: 'ipns id'

runs:
  using: 'node12'
  main: 'dist/index.js'